name: 'dbt_olist' # Nama Project
version: '1.0.0' # Version

profile: 'dbt_olist' # Nama profile di profiles.yml

model-paths: ["models"] # folder tempat file .sql model berada
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"  # folder hasil build dbt
  - "dbt_packages"  # folder dependency packages

models:
  dbt_olist:  # sesuai nama project di atas
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      facts:
        +schema: gold
        +materialized: table
    example:    # subfolder di dalam models/
      +materialized: view  # semua model di sini default jadi view

vars:
  data_path: '../../data/raw'